# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pontifex}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Errin Larsen"]
  s.date = %q{2011-06-01}
  s.default_executable = %q{pontifex}
  s.description = %q{This gem is a solution to ruby quiz #1: http://www.rubyquiz.com/quiz1.html}
  s.email = %q{errinlarsen@gmail.com}
  s.executables = ["pontifex"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/pontifex",
    "cucumber.yml",
    "feature/pontifex_interactive.feature",
    "feature/pontifex_with_files.feature",
    "feature/support/env.rb",
    "lib/pontifex.rb",
    "lib/pontifex/card.rb",
    "lib/pontifex/cipher.rb",
    "lib/pontifex/key_stream.rb",
    "spec/pontifex/card_spec.rb",
    "spec/pontifex/cipher_spec.rb",
    "spec/pontifex/key_stream_spec.rb",
    "spec/pontifex/pontifex_spec.rb",
    "spec/spec_helper.rb",
    "vendor/cache/aruba-0.3.6.gem",
    "vendor/cache/builder-3.0.0.gem",
    "vendor/cache/childprocess-0.1.9.gem",
    "vendor/cache/cucumber-0.10.3.gem",
    "vendor/cache/diff-lcs-1.1.2.gem",
    "vendor/cache/ffi-1.0.9.gem",
    "vendor/cache/gherkin-2.3.9.gem",
    "vendor/cache/git-1.2.5.gem",
    "vendor/cache/jeweler-1.6.0.gem",
    "vendor/cache/json-1.5.1.gem",
    "vendor/cache/rake-0.9.0.gem",
    "vendor/cache/rcov-0.9.9.gem",
    "vendor/cache/rspec-2.6.0.gem",
    "vendor/cache/rspec-core-2.6.3.gem",
    "vendor/cache/rspec-expectations-2.6.0.gem",
    "vendor/cache/rspec-mocks-2.6.0.gem",
    "vendor/cache/term-ansicolor-1.0.5.gem",
    "vendor/cache/trollop-1.16.2.gem"
  ]
  s.homepage = %q{http://github.com/errinlarsen/pontifex}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{An implementation of the Solitaire Cipher in Ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

